version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000" # Maps port 3000 on the host to port 3000 in the container
    env_file:
      - .env # Loads environment variables from a .env file in the same directory
    depends_on:
      - db
    restart: unless-stopped
    # Ensure the app runs as the 'node' user as defined in Dockerfile
    user: "node"

  db:
    image: mysql:8.0 # Using MySQL 8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql # Persistent storage for database data
    restart: unless-stopped
    # Optional: Expose DB port for direct access (e.g., for local dev tools)
    # - "3306:3306"

volumes:
  mysql_data: # Defines the named volume for data persistence
