version: '3.8'

services:
  # Production backend service
  app: 
    build: .
    container_name: tecket_prod_app 
    ports:
      - "3000:3000" # Port 3000
    env_file:
      - .env.prod 
    depends_on:
      db: # The respective db service
        condition: service_healthy
    restart: unless-stopped
    user: "node"
    command: sh -c "npx prisma migrate deploy && npm start"

  # Production database service
  db: 
    image: mysql:8.0
    container_name: tecket_prod_db 
    environment:
      MYSQL_ROOT_PASSWORD: ${PROD_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROD_MYSQL_DATABASE}
      MYSQL_USER: ${PROD_MYSQL_USER}
      MYSQL_PASSWORD: ${PROD_MYSQL_PASSWORD}
    volumes:
      - tecket_prod_mysql_data:/var/lib/mysql # Specific volume for production data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${PROD_MYSQL_USER}", "-p${PROD_MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # To access DB directly from host (optional, ensure port is unique if staging DB also exposed)
    # ports:
    #   - "33060:3306" 

volumes:
  tecket_prod_mysql_data: 
    name: tecket_prod_mysql_data 
